version: "3.8"

services:
  api:
    image: server-nest:v1.0
    container_name: api
    ports:
      - "3002:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true
